# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_graph.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 801)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 800))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QtWidgets.QFrame(self.centralwidget)
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Top_Bar.setFont(font)
        self.Top_Bar.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toggle = QtWidgets.QFrame(self.Top_Bar)
        self.frame_toggle.setMaximumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.frame_toggle.setFont(font)
        self.frame_toggle.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_toggle)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Btn_Toggle = QtWidgets.QPushButton(self.frame_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Toggle.sizePolicy().hasHeightForWidth())
        self.Btn_Toggle.setSizePolicy(sizePolicy)
        self.Btn_Toggle.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Btn_Toggle.setFont(font)
        self.Btn_Toggle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Btn_Toggle.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px solid;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_Toggle.setIcon(icon)
        self.Btn_Toggle.setObjectName("Btn_Toggle")
        self.verticalLayout_2.addWidget(self.Btn_Toggle)
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.frame_top = QtWidgets.QFrame(self.Top_Bar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.frame_top.setFont(font)
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Content.setFont(font)
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.Content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(80, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(4)
        self.frame_left_menu.setFont(font)
        self.frame_left_menu.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.frame_top_menus.setFont(font)
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setContentsMargins(1, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_page_input = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_input.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_page_input.sizePolicy().hasHeightForWidth())
        self.btn_page_input.setSizePolicy(sizePolicy)
        self.btn_page_input.setMinimumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btn_page_input.setFont(font)
        self.btn_page_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_page_input.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/res/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_page_input.setIcon(icon1)
        self.btn_page_input.setObjectName("btn_page_input")
        self.verticalLayout_4.addWidget(self.btn_page_input)
        self.btn_page_output = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_output.setMinimumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btn_page_output.setFont(font)
        self.btn_page_output.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/res/output.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_page_output.setIcon(icon2)
        self.btn_page_output.setCheckable(False)
        self.btn_page_output.setAutoRepeat(False)
        self.btn_page_output.setAutoExclusive(False)
        self.btn_page_output.setObjectName("btn_page_output")
        self.verticalLayout_4.addWidget(self.btn_page_output)
        self.btn_page_gpraph = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_gpraph.setMinimumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btn_page_gpraph.setFont(font)
        self.btn_page_gpraph.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/res/graph.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_page_gpraph.setIcon(icon3)
        self.btn_page_gpraph.setObjectName("btn_page_gpraph")
        self.verticalLayout_4.addWidget(self.btn_page_gpraph)
        self.btn_page_excel = QtWidgets.QPushButton(self.frame_top_menus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_page_excel.sizePolicy().hasHeightForWidth())
        self.btn_page_excel.setSizePolicy(sizePolicy)
        self.btn_page_excel.setMinimumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btn_page_excel.setFont(font)
        self.btn_page_excel.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/res/excel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_page_excel.setIcon(icon4)
        self.btn_page_excel.setObjectName("btn_page_excel")
        self.verticalLayout_4.addWidget(self.btn_page_excel)
        self.verticalLayout_3.addWidget(self.frame_top_menus, 0, QtCore.Qt.AlignTop)
        self.frame_close = QtWidgets.QFrame(self.frame_left_menu)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.frame_close.setFont(font)
        self.frame_close.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_close.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_close.setObjectName("frame_close")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_close)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.btn_close = QtWidgets.QPushButton(self.frame_close)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_close.setFont(font)
        self.btn_close.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_close.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/res/close_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon5)
        self.btn_close.setIconSize(QtCore.QSize(64, 64))
        self.btn_close.setObjectName("btn_close")
        self.verticalLayout_9.addWidget(self.btn_close)
        self.verticalLayout_3.addWidget(self.frame_close, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.Content)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.frame_pages.setFont(font)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Pages_Widget = QtWidgets.QStackedWidget(self.frame_pages)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Pages_Widget.setFont(font)
        self.Pages_Widget.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.Pages_Widget.setObjectName("Pages_Widget")
        self.page_input = QtWidgets.QWidget()
        self.page_input.setObjectName("page_input")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_input)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Pages_Widget.addWidget(self.page_input)
        self.page_output = QtWidgets.QWidget()
        self.page_output.setObjectName("page_output")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_output)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Pages_Widget.addWidget(self.page_output)
        self.page_graph = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_graph.sizePolicy().hasHeightForWidth())
        self.page_graph.setSizePolicy(sizePolicy)
        self.page_graph.setObjectName("page_graph")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_graph)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")




        self.frame_graphics = QtWidgets.QFrame(self.page_graph)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_graphics.sizePolicy().hasHeightForWidth())
        self.frame_graphics.setSizePolicy(sizePolicy)
        self.frame_graphics.setStyleSheet("")
        self.frame_graphics.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_graphics.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_graphics.setObjectName("frame_graphics")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_graphics)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")



        self.frame_chart = QtWidgets.QFrame(self.frame_graphics)
        self.frame_chart.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_chart.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_chart.setLineWidth(8)
        self.frame_chart.setObjectName("frame_chart")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_chart)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_TEST = QtWidgets.QPushButton(self.frame_chart)
        self.btn_TEST.setObjectName("btn_TEST")
        self.horizontalLayout_3.addWidget(self.btn_TEST)
        self.horizontalLayout_4.addWidget(self.frame_chart)
        self.frame_data = QtWidgets.QFrame(self.frame_graphics)
        self.frame_data.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_data.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_data.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_data.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_data.setObjectName("frame_data")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_data)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.lbl_indicator = QtWidgets.QLabel(self.frame_data)
        self.lbl_indicator.setMinimumSize(QtCore.QSize(0, 35))
        self.lbl_indicator.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbl_indicator.setStyleSheet("background-color: rgb(52, 101, 164);\n"
"border: 1px solid;")
        self.lbl_indicator.setObjectName("lbl_indicator")
        self.verticalLayout_12.addWidget(self.lbl_indicator)
        self.frame_graph_indicator = QtWidgets.QFrame(self.frame_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_graph_indicator.sizePolicy().hasHeightForWidth())
        self.frame_graph_indicator.setSizePolicy(sizePolicy)
        self.frame_graph_indicator.setStyleSheet("QFrame {\n"
"border: 1px solid;\n"
"}")
        self.frame_graph_indicator.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_indicator.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_indicator.setObjectName("frame_graph_indicator")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_graph_indicator)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.checkBox_main = QtWidgets.QCheckBox(self.frame_graph_indicator)
        self.checkBox_main.setObjectName("checkBox_main")
        self.verticalLayout_11.addWidget(self.checkBox_main)
        self.checkBox_budget = QtWidgets.QCheckBox(self.frame_graph_indicator)
        self.checkBox_budget.setObjectName("checkBox_budget")
        self.verticalLayout_11.addWidget(self.checkBox_budget)
        self.checkBox_paid = QtWidgets.QCheckBox(self.frame_graph_indicator)
        self.checkBox_paid.setObjectName("checkBox_paid")
        self.verticalLayout_11.addWidget(self.checkBox_paid)
        self.verticalLayout_12.addWidget(self.frame_graph_indicator)
        self.tableWidget = QtWidgets.QTableWidget(self.frame_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setTabletTracking(False)
        self.tableWidget.setAcceptDrops(False)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet("font: 12px;")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setTabKeyNavigation(True)
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setDragDropOverwriteMode(True)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(21)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(75)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_12.addWidget(self.tableWidget)
        self.lbl_update_GPA = QtWidgets.QLabel(self.frame_data)
        self.lbl_update_GPA.setMinimumSize(QtCore.QSize(0, 35))
        self.lbl_update_GPA.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbl_update_GPA.setStyleSheet("background-color: rgb(52, 101, 164);\n"
"border: 1px solid;\n"
"")
        self.lbl_update_GPA.setObjectName("lbl_update_GPA")
        self.verticalLayout_12.addWidget(self.lbl_update_GPA)
        self.btn_graph_update = QtWidgets.QPushButton(self.frame_data)
        self.btn_graph_update.setMinimumSize(QtCore.QSize(0, 35))
        self.btn_graph_update.setMaximumSize(QtCore.QSize(16777215, 35))
        self.btn_graph_update.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_graph_update.setObjectName("btn_graph_update")
        self.verticalLayout_12.addWidget(self.btn_graph_update)
        self.horizontalLayout_4.addWidget(self.frame_data)
        self.verticalLayout_8.addWidget(self.frame_graphics)
        self.frame_graph_btn = QtWidgets.QFrame(self.page_graph)
        self.frame_graph_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_graph_btn.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_graph_btn.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_graph_btn.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_graph_btn.setObjectName("frame_graph_btn")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_graph_btn)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_graph_back = QtWidgets.QPushButton(self.frame_graph_btn)
        self.btn_graph_back.setMinimumSize(QtCore.QSize(110, 45))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_graph_back.setFont(font)
        self.btn_graph_back.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_graph_back.setObjectName("btn_graph_back")
        self.horizontalLayout_5.addWidget(self.btn_graph_back)
        self.btn_output_exit = QtWidgets.QPushButton(self.frame_graph_btn)
        self.btn_output_exit.setMinimumSize(QtCore.QSize(110, 45))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_output_exit.setFont(font)
        self.btn_output_exit.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_output_exit.setObjectName("btn_output_exit")
        self.horizontalLayout_5.addWidget(self.btn_output_exit)
        self.verticalLayout_8.addWidget(self.frame_graph_btn, 0, QtCore.Qt.AlignRight)


        self.Pages_Widget.addWidget(self.page_graph)
        self.verticalLayout_5.addWidget(self.Pages_Widget)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Pages_Widget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Образовательная деятельность СПО"))
        self.Btn_Toggle.setText(_translate("MainWindow", "Меню"))
        self.btn_page_input.setText(_translate("MainWindow", "Ввод"))
        self.btn_page_output.setText(_translate("MainWindow", "Вывод"))
        self.btn_page_gpraph.setText(_translate("MainWindow", "График"))
        self.btn_page_excel.setText(_translate("MainWindow", "Excel"))
        self.btn_TEST.setText(_translate("MainWindow", "PushButton"))
        self.lbl_indicator.setText(_translate("MainWindow", "Показать на графике:"))
        self.checkBox_main.setText(_translate("MainWindow", "Средний балл"))
        self.checkBox_budget.setText(_translate("MainWindow", "Бюджетники"))
        self.checkBox_paid.setText(_translate("MainWindow", "Платники"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "15"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "16"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "17"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "18"))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "19"))
        item = self.tableWidget.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "20"))
        item = self.tableWidget.verticalHeaderItem(20)
        item.setText(_translate("MainWindow", "21"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Код"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Специальность"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "09.02.03 "))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "ПРОГРАММИРОВАНИЕ В КОМПЬЮТЕРНЫХ СИСТЕМАХ\""))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "09.02.04"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "ИНФОРМАЦИОННЫЕ СИСТЕМЫ (ПО ОТРАСЛЯМ)"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "09.02.07 "))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "10.02.01"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "10.02.04 "))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.lbl_update_GPA.setText(_translate("MainWindow", "Обовить средний балл"))
        self.btn_graph_update.setText(_translate("MainWindow", "Обновить"))
        self.btn_graph_back.setText(_translate("MainWindow", "Назад"))
        self.btn_output_exit.setText(_translate("MainWindow", "Выход"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

# Создаем пустой холст
'''
self.Layout_CHART = QtWidgets.QHBoxLayout(self.frame_core_graphic)
self.Layout_CHART.setObjectName("Layout_CHART")
self.Layout_CHART.setSpacing(0)
# Добавляем два главных окна
self.Layout_CHART.addWidget(self.frame_data)
self.Layout_CHART.addWidget(self.frame_chart)

self.sc = MplCanvas(self, width=9.55, height=4, dpi=100)

self.Layout_CHART.addWidget(self.sc)
'''